<?php

// This file was generated by running "composer dump-env prod"

return array(
  'APP_ENV' => 'prod',
  'APP_SECRET' => '5b7c9a35a593e1acfe0822888f5183be',
  'DATABASE_URL'=>"mysql://root:@127.0.0.1:3306/weblack?serverVersion=mariadb-10.4.11&charset=utf8",

  // 'DATABASE_URL' => 'mysql://dbu129022:5b7c9a35a593e1acfe0822888f5183be@db5007865376.hosting-data.io:3306/dbs6523025?serverVersion=mariadb-10.4.11&charset=utf8',
);
