<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLLvrfAg\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLLvrfAg/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerLLvrfAg.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerLLvrfAg\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerLLvrfAg\App_KernelProdContainer([
    'container.build_hash' => 'LLvrfAg',
    'container.build_id' => 'dd54bcea',
    'container.build_time' => 1653921235,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLLvrfAg');
